version: '2'

services:
 rabbitmq1:
  image: rabbitmq:3-management
  container_name: rabbitmq1
  hostname: rabbitmq1
  ports:
   - "15672:15672"
  networks: 
   - custom-network
  volumes:
   - '/var/lib/rabbitmq/mydata'
  environment:
   - RABBITMQ_ERLANG_COOKIE="AKFDGFGPCLNMEQGKTBHGDSQALR"
   - RABBITMQ_DEFAULT_USER=user
   - RABBITMQ_DEFAULT_PASS=pass

networks:
 custom-network: